// <auto-generated by="the Blazor I18n Text compiler" />
namespace KlipTok.Client.I18nText
{
    public partial class KlipTok : global::Toolbelt.Blazor.I18nText.Interfaces.I18nTextFallbackLanguage, global::Toolbelt.Blazor.I18nText.Interfaces.I18nTextLateBinding
    {
        string global::Toolbelt.Blazor.I18nText.Interfaces.I18nTextFallbackLanguage.FallBackLanguage => "en-US";

        public string this[string key] => global::Toolbelt.Blazor.I18nText.I18nTextExtensions.GetFieldValue(this, key);

        /// <summary>"About"</summary>
        public string About;

        /// <summary>"{0} on Twitch"</summary>
        public string ActionOnTwitchTemplate;

        /// <summary>"Add Clips for this Streamer"</summary>
        public string AddClipsForThisStreamer;

        /// <summary>"Legg til klipp for denne streameren"</summary>
        public string AddklippForThisStreamer;

        /// <summary>"Advanced Filtering"</summary>
        public string AdvancedFiltering;

        /// <summary>"All Streamers"</summary>
        public string AllStreamers;

        /// <summary>"Your authentication with Twitch and KlipTok is no longer valid.  Please login to KlipTok with Twitch to continue."</summary>
        public string AuthenticationIsNoLongerValid;

        /// <summary>"Auto-play videos on scroll"</summary>
        public string AutoPlayVideosOnScroll;

        /// <summary>"At {0} {1} wrote:"</summary>
        public string ByLineFormat;

        /// <summary>"Streamer"</summary>
        public string Channel;

        /// <summary>"Channels Indexed"</summary>
        public string ChannelsIndexed;

        /// <summary>"Click to Follow"</summary>
        public string ClickToFollow;

        /// <summary>"Click to Unfollow"</summary>
        public string ClickToUnfollow;

        /// <summary>"This clip has a transcription that can be searched"</summary>
        public string ClipHasTranscription;

        /// <summary>"Clipped by {0}"</summary>
        public string ClippedByFormat;

        /// <summary>"Clips By Date"</summary>
        public string ClipsByDate;

        /// <summary>"Clips by Day of Week"</summary>
        public string ClipsByDayOfWeek;

        /// <summary>"Clips Created in last 90 days"</summary>
        public string ClipsCreatedLast90Days;

        /// <summary>"Clips Created per Week"</summary>
        public string ClipsCreatedPerWeek;

        /// <summary>"Clips from:"</summary>
        public string ClipsFromLabel;

        /// <summary>"Clips I Like"</summary>
        public string ClipsILike;

        /// <summary>"Clips"</summary>
        public string ClipsTab;

        /// <summary>"Clips Transcribed By Date"</summary>
        public string ClipsTranscribedByDate;

        /// <summary>"Clip Transcription by AssemblyAI:"</summary>
        public string ClipTranscriptionByAssemblyAI;

        /// <summary>"Clip Views"</summary>
        public string ClipViews;

        /// <summary>"Close"</summary>
        public string Close;

        /// <summary>"Comment"</summary>
        public string CommentButton;

        /// <summary>"Comments"</summary>
        public string Comments;

        /// <summary>"[ Danger Zone ]"</summary>
        public string DangerZone;

        /// <summary>"Dark Mode"</summary>
        public string DarkMode;

        /// <summary>"Dashboard"</summary>
        public string DashboardTab;

        /// <summary>"End Date"</summary>
        public string DateRangePicker_End;

        /// <summary>"Start Date"</summary>
        public string DateRangePicker_Start;

        /// <summary>"Discover Clips"</summary>
        public string DiscoverClips;

        /// <summary>"Finn klipp"</summary>
        public string Discoverklipp;

        /// <summary>"Discover Popular Clips"</summary>
        public string DiscoverPopularClips;

        /// <summary>"Finn populære klipp"</summary>
        public string DiscoverPopularklipp;

        /// <summary>"KlipTok does not keep separate user information from Twitch, and is built as a service to augment Twitch Clips."</summary>
        public string DoesNotKeepSeparateUserInformation;

        /// <summary>"Enter new Comment..."</summary>
        public string EnterNewComment;

        /// <summary>"An error occurred while loading."</summary>
        public string ErrorWhileLoading;

        /// <summary>"Exclude these channels"</summary>
        public string ExcludeChannels;

        /// <summary>"Following"</summary>
        public string Favorites;

        /// <summary>"Feedback"</summary>
        public string Feedback;

        /// <summary>"Filter"</summary>
        public string FilterButton;

        /// <summary>"Filter by Category"</summary>
        public string FilterByCategory;

        /// <summary>"Followed Streamers"</summary>
        public string FollowedStreamers;

        /// <summary>"Forever"</summary>
        public string Forever;

        /// <summary>"Forgotten as of : {0}"</summary>
        public string ForgottenAsOfTemplate;

        /// <summary>"Include these channels"</summary>
        public string IncludeChannels;

        /// <summary>"Index my Clips"</summary>
        public string IndexClipsOfMyChannel;

        /// <summary>"indeks mine klipp"</summary>
        public string IndexklippOfMyChannel;

        /// <summary>"In reply to: {0}"</summary>
        public string InReplyToTemplate;

        /// <summary>"Insert Coin"</summary>
        public string InsertCoin;

        /// <summary>"klipp fra:"</summary>
        public string klippFromLabel;

        /// <summary>"klipp jeg liker"</summary>
        public string klippILike;

        /// <summary>"KlipTok Content Placeholder"</summary>
        public string KlipTokContentPlaceholder;

        /// <summary>"Last Clip:"</summary>
        public string LastClip;

        /// <summary>"Last Clip Added:"</summary>
        public string LastClipAdded;

        /// <summary>"Latest"</summary>
        public string Latest;

        /// <summary>"Liked By:"</summary>
        public string LikedBy;

        /// <summary>"Liked Clips"</summary>
        public string LikedClips;

        /// <summary>"Likte klipp"</summary>
        public string Likedklipp;

        /// <summary>"Likes"</summary>
        public string Likes;

        /// <summary>"LIVE"</summary>
        public string Live;

        /// <summary>"Live on Twitch now!"</summary>
        public string LiveOnTwitch;

        /// <summary>"Loading..."</summary>
        public string Loading;

        /// <summary>"Logged Out from KlipTok and Twitch"</summary>
        public string LoggedOutFromKlipTokAndTwitch;

        /// <summary>"Login to KlipTok with Twitch"</summary>
        public string LoginToKlipTokWithTwitch;

        /// <summary>"Login with Twitch"</summary>
        public string LoginWithTwitch;

        /// <summary>"Login with Twitch to Comment"</summary>
        public string LoginWithTwitchToComment;

        /// <summary>"Logout"</summary>
        public string Logout;

        /// <summary>"KlipTok does not have a record of this Clip.  It either does not exist or the Twitch channel has opted out of participating on KlipTok."</summary>
        public string MissingClipError;

        /// <summary>"Most Liked Clippers"</summary>
        public string MostLikedClippers;

        /// <summary>"Most Viewed Categories"</summary>
        public string MostViewedCategories;

        /// <summary>"Most Viewed Clippers"</summary>
        public string MostViewedClippers;

        /// <summary>"Muted Streamers"</summary>
        public string MutedChannels;

        /// <summary>"Muted Until"</summary>
        public string MutedUntil;

        /// <summary>"Mute for:"</summary>
        public string MuteForLabel;

        /// <summary>"Clips from channels I follow"</summary>
        public string MyFavoriteChannels;

        /// <summary>"New Channels Today"</summary>
        public string NewChannelsToday;

        /// <summary>"Next Page"</summary>
        public string NextPage;

        /// <summary>"No Clips Available"</summary>
        public string NoClipsAvailable;

        /// <summary>"Ingen klipp tilgjengelig"</summary>
        public string NoklippAvailable;

        /// <summary>"You haven&apos;t liked any Clips on KlipTok yet!"</summary>
        public string NoLikedClips;

        /// <summary>"Du har ikke likt noen klipp på KlipTok enda!"</summary>
        public string NoLikedklipp;

        /// <summary>"Unmute"</summary>
        public string NoMute;

        /// <summary>"No profile pic available"</summary>
        public string NoProfilePicAvailable;

        /// <summary>"Please note: if you add Clips for this streamer, we kindly request you notify them that you have added their Clips to this site.  We have no direct way to reach out to the broadcaster."</summary>
        public string NotifyOnOptIn;

        /// <summary>"Unable to display records of accounts you follow on Twitch because you are not logged in with a Twitch account.  Please login and sync your followed streamers with KlipTok to access this functionality."</summary>
        public string NotLoggedIn;

        /// <summary>"Opted out of indexing on: {0}"</summary>
        public string OptedOutDateTemplate;

        /// <summary>"Preview Thumbnail for the clip &apos;{0}&apos;"</summary>
        public string PreviewThumbnailForClip;

        /// <summary>"Previous Page"</summary>
        public string PreviousPage;

        /// <summary>"{0} profile pic"</summary>
        public string ProfilePicTemplate;

        /// <summary>"PUBLIC BETA"</summary>
        public string PublicBeta;

        /// <summary>"Recorded {0}"</summary>
        public string Recorded;

        /// <summary>"Remove my content from KlipTok"</summary>
        public string RemoveMyContentFromKlipTok;

        /// <summary>"Reply"</summary>
        public string Reply;

        /// <summary>"Reset"</summary>
        public string ResetButton;

        /// <summary>"Retry"</summary>
        public string RetryButton;

        /// <summary>"Right to forget"</summary>
        public string RightToForget;

        /// <summary>"You have the right to request KlipTok forgets all information that you have shared.  By clicking this link and confirming, KlipTok will remove all of your Comments, Likes, and Clips."</summary>
        public string RightToForgetDescription;

        /// <summary>"Save my changes"</summary>
        public string SaveMyChanges;

        /// <summary>"Score"</summary>
        public string Score;

        /// <summary>"Search all of KlipTok for {0}"</summary>
        public string SearchAllOfKlipTok;

        /// <summary>"Search"</summary>
        public string SearchButton;

        /// <summary>"Results from clip title search for text: {0}"</summary>
        public string SearchedClipTitlesAndFoundTemplate;

        /// <summary>"We searched KlipTok for &quot;{0}&quot; and found:"</summary>
        public string SearchedKlipTokAndFoundTemplate;

        /// <summary>"Search for a Streamer..."</summary>
        public string SearchForChannel;

        /// <summary>"Search KlipTok..."</summary>
        public string SearchKlipTok;

        /// <summary>"{0} not found"</summary>
        public string SearchNotFoundFormat;

        /// <summary>"Search Results"</summary>
        public string SearchResults;

        /// <summary>"Results from clip transcription search for text: {0}"</summary>
        public string SearchResultsFromTranscriptionSearch;

        /// <summary>"Select a Category"</summary>
        public string SelectCategory;

        /// <summary>"Share Streamer"</summary>
        public string ShareStreamer;

        /// <summary>"Share this Clip"</summary>
        public string ShareThisClip;

        /// <summary>"Sort by:"</summary>
        public string SortByLabel;

        /// <summary>"Streamer is muted until: {0}"</summary>
        public string StreamerIsMutedUntilTemplate;

        /// <summary>"{0} playing {1}"</summary>
        public string StreamerPlayingCategoryTemplate;

        /// <summary>"Suggested Streamers"</summary>
        public string SuggestedStreamers;

        /// <summary>"Sync Followed Streamers with KlipTok"</summary>
        public string SyncFollowersWithKlipTok;

        /// <summary>"We&apos;re making details about the growth of KlipTok openly available for you to review."</summary>
        public string SystemDashboardDescription;

        /// <summary>"System Status Dashboard"</summary>
        public string SystemStatusDashboard;

        /// <summary>"Day Created"</summary>
        public string TitleDayCreated;

        /// <summary>"Total Channels Identified"</summary>
        public string TotalChannelsIdentified;

        /// <summary>"Total Clips"</summary>
        public string TotalClips;

        /// <summary>"Total Clips on KlipTok"</summary>
        public string TotalClipsOnKlipTok;

        /// <summary>"Total Clips Transcribed"</summary>
        public string TotalClipsTranscribed;

        /// <summary>"Total Comments across all Clips"</summary>
        public string TotalCommentsAcrossAllClips;

        /// <summary>"Totalt antall kommentarer over alle klipp"</summary>
        public string TotalCommentsAcrossAllklipp;

        /// <summary>"Totalt antal klipp på KlipTok"</summary>
        public string TotalklippOnKlipTok;

        /// <summary>"Total Likes across all Clips"</summary>
        public string TotalLikesAcrossAllClips;

        /// <summary>"Totalt antall likes over alle klipp"</summary>
        public string TotalLikesAcrossAllklipp;

        /// <summary>"Total views across all Clips"</summary>
        public string TotalViewsAcrossAllClips;

        /// <summary>"Totalt antal visningar over alle klipp"</summary>
        public string TotalViewsAcrossAllklipp;

        /// <summary>"Try clicking the heart icon {0} below a Clip to &apos;Like&apos; it and we&apos;ll report it here for you so you can easily find it again in the future"</summary>
        public string TryLikeButtonTemplate;

        /// <summary>"Twitch Streamers I Follow"</summary>
        public string TwitchChannelsIFollow;

        /// <summary>"{0} liked {1}"</summary>
        public string UserLikedTimeTemplate;

        /// <summary>"User Profile"</summary>
        public string UserProfile;

        /// <summary>"Views"</summary>
        public string Views;
    }
}
